POST http://localhost:8080/registerUser
Content-Type: application/json

{
  "username": "Pascal",
  "password": "Berg"
}

###

POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "Pascal",
  "password": "Berg"
}

###
